export const USER_CREATING = 'USER_CREATING'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_ERROR = 'USER_CREATE_ERROR'

export const USER_REQUESTING = 'USER_REQUESTING'
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS'
export const USER_REQUEST_ERROR = 'USER_REQUEST_ERROR'
